UPDATE SYS_CONFIG SET VALUE = REPLACE(VALUE, 'tcp:', 'ssl:'), DEFAULT_VALUE = REPLACE(DEFAULT_VALUE, 'tcp:', 'ssl:') WHERE CONFIG_KEY = 'activemq.broker.connector.bindAddress';
UPDATE SYS_CONFIG SET VALUE = REPLACE(VALUE, 'tcp:', 'ssl:'), DEFAULT_VALUE = REPLACE(DEFAULT_VALUE, 'tcp:', 'ssl:') WHERE CONFIG_KEY = 'config.activeMQConnectionFactory.brokerURL';
UPDATE ACCESS_CONTROL SET REQUEST_METHOD = 'DELETE' WHERE URL_PATTERN = '/api/v1/tools/location/delete';

MERGE INTO SYS_CONFIG USING (SELECT 1 FROM SYSIBM.SYSDUMMY1) ON (APPLICATION = 'application' AND CONFIG_KEY = 'activemq.broker.ssl.enabled')
WHEN MATCHED THEN UPDATE SET VALUE = 'true', DEFAULT_VALUE = 'true', VALUE_FORMAT = '', MAIN_GROUP = 'engine', SUB_GROUP = 'configServer', MAIN_GROUP_ORDER = '30', SUB_GROUP_ORDER = '0', CONFIG_ORDER = '4', HIDDEN = '1', READ_ONLY = '0', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '1', DATA_TYPE = 'boolean', FIELD_TYPE = 'checkbox' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'Enable/Disable ActiveMQ broker SSL connection.', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'application', 'activemq.broker.ssl.enabled', 'true', 'true', '', 'engine', 'configServer', '30', '0', '4', '1', '0', '1', '0', '0', '1', 'boolean', 'checkbox', '', '1', '', 'Enable/Disable ActiveMQ broker SSL connection.', CURRENT_TIMESTAMP, '-1' );

MERGE INTO SYS_CONFIG USING (SELECT 1 FROM SYSIBM.SYSDUMMY1) ON (APPLICATION = 'app-home' AND CONFIG_KEY = 'spring.security.oauth2.resourceserver.jwt.issuer-uri')
WHEN MATCHED THEN UPDATE SET VALUE = '${server.name}/cas/oidc', DEFAULT_VALUE = '${server.name}/cas/oidc', VALUE_FORMAT = '', MAIN_GROUP = 'security', SUB_GROUP = 'app-home', MAIN_GROUP_ORDER = '40', SUB_GROUP_ORDER = '130', CONFIG_ORDER = '0', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '0', DATA_TYPE = 'text', FIELD_TYPE = 'text' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'JWT Issuer URI', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'app-home', 'spring.security.oauth2.resourceserver.jwt.issuer-uri', '${server.name}/cas/oidc', '${server.name}/cas/oidc', '', 'security', 'app-home', '40', '130', '0', '1', '1', '1', '0', '0', '0', 'text', 'text', '', '1', '', 'JWT Issuer URI', CURRENT_TIMESTAMP, '-1' );

MERGE INTO SYS_CONFIG USING (SELECT 1 FROM SYSIBM.SYSDUMMY1) ON (APPLICATION = 'app-home' AND CONFIG_KEY = 'spring.security.oauth2.resourceserver.jwt.jwk-set-uri')
WHEN MATCHED THEN UPDATE SET VALUE = '${server.name}/cas/oidc/jwks', DEFAULT_VALUE = '${server.name}/cas/oidc/jwks', VALUE_FORMAT = '', MAIN_GROUP = 'security', SUB_GROUP = 'app-home', MAIN_GROUP_ORDER = '40', SUB_GROUP_ORDER = '130', CONFIG_ORDER = '10', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '0', DATA_TYPE = 'text', FIELD_TYPE = 'text' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'JWK URI', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'app-home', 'spring.security.oauth2.resourceserver.jwt.jwk-set-uri', '${server.name}/cas/oidc/jwks', '${server.name}/cas/oidc/jwks', '', 'security', 'app-home', '40', '130', '10', '1', '1', '1', '0', '0', '0', 'text', 'text', '', '1', '', 'JWK URI', CURRENT_TIMESTAMP, '-1' );

MERGE INTO SYS_CONFIG USING (SELECT 1 FROM SYSIBM.SYSDUMMY1) ON (APPLICATION = 'config-service' AND CONFIG_KEY = 'client.applications')
WHEN MATCHED THEN UPDATE SET VALUE = 'console,cas,reporter,administrator,dabs,dac,dcsf,dem,dkms,dms,dps,policy-controller-manager,service-manager,app-home', DEFAULT_VALUE = 'console,cas,reporter,administrator,dabs,dac,dcsf,dem,dkms,dms,dps,policy-controller-manager,service-manager,app-home', VALUE_FORMAT = '', MAIN_GROUP = 'engine', SUB_GROUP = 'configClient', MAIN_GROUP_ORDER = '30', SUB_GROUP_ORDER = '1', CONFIG_ORDER = '0', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '0', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '1', DATA_TYPE = 'text', FIELD_TYPE = 'multi-value' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'Configuration updates will be sent to the specified applications only.', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'config-service', 'client.applications', 'console,cas,reporter,administrator,dabs,dac,dcsf,dem,dkms,dms,dps,policy-controller-manager,service-manager,app-home', 'console,cas,reporter,administrator,dabs,dac,dcsf,dem,dkms,dms,dps,policy-controller-manager,service-manager,app-home', '', 'engine', 'configClient', '30', '1', '0', '1', '1', '0', '0', '0', '1', 'text', 'multi-value', '', '1', '', 'Configuration updates will be sent to the specified applications only.', CURRENT_TIMESTAMP, '-1' );

CREATE TABLE APPLICATION (
    ID                  BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
                           START WITH +1  
                           INCREMENT BY +1  
                           MINVALUE +1  
                           MAXVALUE +9223372036854775807  
                           NO CYCLE  
                           CACHE 20  
                           NO ORDER ),
    NAME                VARCHAR(255),
    APPLICATION_ORDER   INTEGER,
    ICON_URL            VARCHAR(255),
    URL                 VARCHAR(255),
    CONSTRAINT APPLICATION_PK PRIMARY KEY ( ID )
);

INSERT INTO APPLICATION (ID,APPLICATION_ORDER,ICON_URL,NAME,URL) VALUES
	 (HIBERNATE_SEQUENCE.NEXTVAL,100,'/assets/img/policy-studio-icon.svg','Policy Studio','${server.name}/console');
INSERT INTO APPLICATION (ID,APPLICATION_ORDER,ICON_URL,NAME,URL) VALUES
	 (HIBERNATE_SEQUENCE.NEXTVAL,300,'/assets/img/system-administration-icon.svg','System Administration','${server.name}/services/#/dashboard');
INSERT INTO APPLICATION (ID,APPLICATION_ORDER,ICON_URL,NAME,URL) VALUES
	 (HIBERNATE_SEQUENCE.NEXTVAL,200,'/assets/img/audit-report-icon.svg','Audit and Report','${server.name}/reporter');

CREATE TABLE MENU_ITEM (
    ID                 BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
                          START WITH +1  
                          INCREMENT BY +1  
                          MINVALUE +1  
                          MAXVALUE +9223372036854775807  
                          NO CYCLE  
                          CACHE 20  
                          NO ORDER ),
    APPLICATION        VARCHAR(255),
    MENU_ITEM_NAME     VARCHAR(255),
    MENU_ITEM_ORDER    INTEGER,
    MAIN_GROUP         VARCHAR(255),
    MAIN_GROUP_ORDER   INTEGER,
    SUB_GROUP          VARCHAR(255),
    SUB_GROUP_ORDER    INTEGER,
    PERMISSIONS        VARCHAR(255),
    URL                VARCHAR(255),
    CONSTRAINT MENU_ITEM_KEY PRIMARY KEY ( ID )
);

INSERT INTO MENU_ITEM (ID,APPLICATION,MAIN_GROUP,MAIN_GROUP_ORDER,MENU_ITEM_NAME,MENU_ITEM_ORDER,PERMISSIONS,SUB_GROUP,SUB_GROUP_ORDER,URL) VALUES
	 (HIBERNATE_SEQUENCE.NEXTVAL,'Administrator','Policy Controllers',100,'Status',100,'',NULL,NULL,'${server.name}/policy-controllers/#/status');
INSERT INTO MENU_ITEM (ID,APPLICATION,MAIN_GROUP,MAIN_GROUP_ORDER,MENU_ITEM_NAME,MENU_ITEM_ORDER,PERMISSIONS,SUB_GROUP,SUB_GROUP_ORDER,URL) VALUES
	 (HIBERNATE_SEQUENCE.NEXTVAL,'Administrator','Policy Controllers',100,'Profiles',100,'MANAGE_POLICY_CONTROLLER',NULL,NULL,'${server.name}/policy-controllers/#/profiles');
INSERT INTO MENU_ITEM (ID,APPLICATION,MAIN_GROUP,MAIN_GROUP_ORDER,MENU_ITEM_NAME,MENU_ITEM_ORDER,PERMISSIONS,SUB_GROUP,SUB_GROUP_ORDER,URL) VALUES
	 (HIBERNATE_SEQUENCE.NEXTVAL,'Administrator','ICENets',200,'Status',100,'MANAGE_ICENET',NULL,NULL,'${server.name}/services/#/icenet/status');

UPDATE ACCESS_CONTROL SET REQUEST_METHOD = 'PUT' WHERE URL_PATTERN = '/api/v1/enrollment/upload/{id:[0-9]+}';

UPDATE SYS_CONFIG SET MAIN_GROUP = 'general' WHERE APPLICATION = 'console' AND MAIN_GROUP = 'reporter';
UPDATE SYS_CONFIG SET MAIN_GROUP = 'auth' WHERE APPLICATION = 'cas' AND CONFIG_KEY  LIKE '%cas.authn.pm.reset%';
UPDATE SYS_CONFIG SET MAIN_GROUP = 'auth' WHERE SUB_GROUP = 'user.acc' or SUB_GROUP = 'mfa';
UPDATE SYS_CONFIG SET MAIN_GROUP = 'app' WHERE MAIN_GROUP = 'general' AND SUB_GROUP = 'remote.env' OR SUB_GROUP = 'policy.workflow';
UPDATE SYS_CONFIG SET MAIN_GROUP = 'app' WHERE SUB_GROUP = 'data.transportation' OR MAIN_GROUP = 'dac' or MAIN_GROUP = 'reporter';

UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 10 WHERE MAIN_GROUP = 'general' AND SUB_GROUP = 'url';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 30 WHERE MAIN_GROUP = 'general' AND SUB_GROUP = 'mail';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 65 WHERE MAIN_GROUP = 'general' AND SUB_GROUP = 'help';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 80 WHERE MAIN_GROUP = 'general' AND SUB_GROUP = 'console.dashboard';

UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 10 WHERE MAIN_GROUP = 'auth' AND SUB_GROUP = 'user.acc';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 30 WHERE MAIN_GROUP = 'auth' AND SUB_GROUP = 'pm';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 40 WHERE MAIN_GROUP = 'auth' AND SUB_GROUP = 'mfa';

UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 10 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'remote.env';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 20 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'policy.workflow';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 30 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'data.transportation';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 40 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'reporter.config';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 50 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'archive';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 60 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'index';
UPDATE SYS_CONFIG SET SUB_GROUP_ORDER = 70 WHERE MAIN_GROUP = 'app' AND SUB_GROUP = 'sync';

UPDATE SYS_CONFIG SET MAIN_GROUP_ORDER = 10 WHERE MAIN_GROUP = 'general';
UPDATE SYS_CONFIG SET MAIN_GROUP_ORDER = 20 WHERE MAIN_GROUP = 'app';
UPDATE SYS_CONFIG SET MAIN_GROUP_ORDER = 30 WHERE MAIN_GROUP = 'auth';
UPDATE SYS_CONFIG SET MAIN_GROUP_ORDER = 40 WHERE MAIN_GROUP = 'security';

-- Rather than checking to see if the tables exist, we'll just attempt
-- to create them and catch the error (42701)

begin
  declare continue handler for sqlstate '42701' begin end&semi
  execute immediate 'CREATE TABLE ARCHIVE_DICT_ELEMENTS( ID BIGINT NOT NULL, VERSION INTEGER NOT NULL, ORIGINAL_ID BIGINT, ENROLLMENT_ID BIGINT NOT NULL, DICTIONARY_KEY VARCHAR(900), UNIQUE_NAME NVARCHAR(128), displayName NVARCHAR(128), PATH VARCHAR(900) NOT NULL, PATH_HASH BIGINT NOT NULL, REPARENTED CHAR(1), ACTIVE_FROM BIGINT NOT NULL, ACTIVE_TO BIGINT NOT NULL )'&semi
END;

begin
  declare continue handler for sqlstate '42701' begin end&semi
  execute immediate 'CREATE TABLE ARCHIVE_DICT_ENUM_GROUP_MEMBERS( ID BIGINT NOT NULL, VERSION INTEGER NOT NULL, FROM_ID BIGINT NOT NULL, TO_ID BIGINT, ENROLLMENT_ID BIGINT NOT NULL, IS_DIRECT CHAR(1) NOT NULL, ACTIVE_FROM BIGINT NOT NULL, ACTIVE_TO BIGINT NOT NULL )'&semi
END;

begin
  declare continue handler for sqlstate '42701' begin end&semi
  execute immediate 'CREATE TABLE ARCHIVE_DICT_ENUM_GROUPS(ELEMENT_ID BIGINT NOT NULL)'&semi
END;

begin
  declare continue handler for sqlstate '42701' begin end&semi
  execute immediate 'CREATE TABLE ARCHIVE_DICT_ENUM_MEMBERS( ID BIGINT NOT NULL, VERSION INTEGER NOT NULL, GROUP_ID BIGINT NOT NULL, MEMBER_ID BIGINT NOT NULL, ELEMENT_TYPE_ID BIGINT NOT NULL, ENROLLMENT_ID BIGINT NOT NULL, ACTIVE_FROM BIGINT NOT NULL, ACTIVE_TO BIGINT NOT NULL )'&semi
END;

begin
  declare continue handler for sqlstate '42701' begin end&semi
  execute immediate 'CREATE TABLE ARCHIVE_DICT_STRUCT_GROUPS(ELEMENT_ID BIGINT NOT NULL, FILTER NVARCHAR(900), filterLength INTEGER)'&semi
END;

begin
  declare continue handler for sqlstate '42701' begin end&semi
  execute immediate 'CREATE TABLE ARCHIVE_DICT_LEAF_ELEMENTS( element_id BIGINT NOT NULL, TYPE_ID BIGINT NOT NULL, String00 NVARCHAR(4000), String01 NVARCHAR(4000), String02 NVARCHAR(4000), String03 NVARCHAR(4000), String04 NVARCHAR(4000), String05 NVARCHAR(4000), String06 NVARCHAR(4000), String07 NVARCHAR(4000), String08 NVARCHAR(4000), String09 NVARCHAR(4000), String10 NVARCHAR(4000), String11 NVARCHAR(4000), String12 NVARCHAR(4000), String13 NVARCHAR(4000), String14 NVARCHAR(4000), String15 NVARCHAR(4000), String16 NVARCHAR(4000), String17 NVARCHAR(4000), String18 NVARCHAR(4000), String19 NVARCHAR(4000), String20 NVARCHAR(4000), String21 NVARCHAR(4000), String22 NVARCHAR(4000), String23 NVARCHAR(4000), String24 NVARCHAR(4000), String25 NVARCHAR(4000), String26 NVARCHAR(4000), String27 NVARCHAR(4000), String28 NVARCHAR(4000), String29 NVARCHAR(4000), String30 NVARCHAR(4000), String31 NVARCHAR(4000), String32 NVARCHAR(4000), String33 NVARCHAR(4000), String34 NVARCHAR(4000), String35 NVARCHAR(4000), String36 NVARCHAR(4000), String37 NVARCHAR(4000), String38 NVARCHAR(4000), String39 NVARCHAR(4000), String40 NVARCHAR(4000), String41 NVARCHAR(4000), String42 NVARCHAR(4000), String43 NVARCHAR(4000), String44 NVARCHAR(4000), String45 NVARCHAR(4000), String46 NVARCHAR(4000), String47 NVARCHAR(4000), String48 NVARCHAR(4000), String49 NVARCHAR(4000), Number00 BIGINT, Number01 BIGINT, Number02 BIGINT, Number03 BIGINT, Number04 BIGINT, Number05 BIGINT, Number06 BIGINT, Number07 BIGINT, Number08 BIGINT, Number09 BIGINT, Number10 BIGINT, Number11 BIGINT, Number12 BIGINT, Number13 BIGINT, Number14 BIGINT, Number15 BIGINT, Number16 BIGINT, Number17 BIGINT, Number18 BIGINT, Number19 BIGINT, Date00 BIGINT, Date01 BIGINT, Date02 BIGINT, Date03 BIGINT, Date04 BIGINT, Date05 BIGINT, Date06 BIGINT, Date07 BIGINT, Date08 BIGINT, Date09 BIGINT, Date10 BIGINT, Date11 BIGINT, Date12 BIGINT, Date13 BIGINT, Date14 BIGINT, Date15 BIGINT, Date16 BIGINT, Date17 BIGINT, Date18 BIGINT, Date19 BIGINT, NUMARRAY00 NVARCHAR(2048), NUMARRAY01 NVARCHAR(2048), NUMARRAY02 NVARCHAR(2048), NUMARRAY03 NVARCHAR(2048))'&semi
END;

MERGE INTO SYS_CONFIG USING (SELECT 1 FROM SYSIBM.SYSDUMMY1) ON (APPLICATION = 'policy-controller-manager' AND CONFIG_KEY = 'db.comboPooledDataSource.idleConnectionTestPeriod')
WHEN MATCHED THEN UPDATE SET VALUE = '30', DEFAULT_VALUE = '30', VALUE_FORMAT = '', MAIN_GROUP = 'db', SUB_GROUP = 'policy-controller-manager', MAIN_GROUP_ORDER = '20', SUB_GROUP_ORDER = '20', CONFIG_ORDER = '10', HIDDEN = '1', READ_ONLY = '0', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '1', DATA_TYPE = 'integer', FIELD_TYPE = 'number' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = '', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'policy-controller-manager', 'db.comboPooledDataSource.idleConnectionTestPeriod', '30', '30', '', 'db', 'policy-controller-manager', '20', '20', '10', '1', '0', '1', '0', '0', '1', 'integer', 'number', '', '1', '', '', CURRENT_TIMESTAMP, '-1' );

MERGE INTO SYS_CONFIG USING (SELECT 1 FROM SYSIBM.SYSDUMMY1) ON (APPLICATION = 'service-manager' AND CONFIG_KEY = 'db.comboPooledDataSource.idleConnectionTestPeriod')
WHEN MATCHED THEN UPDATE SET VALUE = '30', DEFAULT_VALUE = '30', VALUE_FORMAT = '', MAIN_GROUP = 'db', SUB_GROUP = 'service-manager', MAIN_GROUP_ORDER = '20', SUB_GROUP_ORDER = '30', CONFIG_ORDER = '10', HIDDEN = '1', READ_ONLY = '0', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '1', DATA_TYPE = 'integer', FIELD_TYPE = 'number' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = '', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, 'service-manager', 'db.comboPooledDataSource.idleConnectionTestPeriod', '30', '30', '', 'db', 'service-manager', '20', '30', '10', '1', '0', '1', '0', '0', '1', 'integer', 'number', '', '1', '', '', CURRENT_TIMESTAMP, '-1' );

