ALTER TABLE MFA_GOOGLE_AUTH_ACCOUNT ADD COLUMN ACCOUNT_NAME VARCHAR(25 BYTE) DEFAULT 'no_name' NOT NULL;
UPDATE WORKFLOW_LEVEL SET NAME='Policy Workflow', DESCRIPTION='' WHERE NAME='Approval level 1';
