UPDATE SYS_CONFIG SET VALUE = 'https://docs.nextlabs.com/cc/2020.07' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'help.url.base';
UPDATE SYS_CONFIG SET VALUE = 'unique_name', DEFAULT_VALUE = 'unique_name' WHERE CONFIG_KEY LIKE 'cas.authn.pac4j.oidc[%].principalAttributeId' AND VALUE = 'upn';
DELETE FROM SYS_CONFIG WHERE CONFIG_KEY = 'context.parameter.EnforcePasswordHistory';

INSERT INTO SYS_CONFIG (APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY) VALUES ('console', 'dashboard.widget.refresh.interval', '30', '30', '', 'reporter', 'console.dashboard', 65, 10, 110, 0, 0, 1, 1, 0, 0, 'integer', 'number', '', 1, '^[0-9]+$', 'Refresh interval of Dashboard system configuration status and recent activities, in seconds.', CURRENT_TIMESTAMP, -1);

INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/secureStore/replaceStoreFile', 'hasAuthority(''MANAGE_SECURE_STORE'')');

UPDATE SYS_CONFIG SET VALUE = '9200', DEFAULT_VALUE = '9200' WHERE APPLICATION = 'console' AND CONFIG_KEY = 'search.engine.port';

INSERT INTO SYS_CONFIG (APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY) VALUES ('dms', 'dac.index.rebuild.days.of.month', '', '', '', 'dac', 'index', 80, 0, 4, 0, 0, 0, 0, 0, 1, 'text', 'text', '', 0, '', 'Comma separated list of days of the month on which to run sync operations (e.g. 1,2,3)', CURRENT_TIMESTAMP, -1);
UPDATE SYS_CONFIG SET CONFIG_ORDER = '5' WHERE CONFIG_KEY = 'dac.index.rebuild.timeout.minutes';

IF ((SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'STRING00' and TABLE_NAME = 'DICT_LEAF_ELEMENTS') = 4000)
BEGIN
  IF ((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'STRING20' AND TABLE_NAME = 'DICT_LEAF_ELEMENTS')=0)
  BEGIN
    ALTER TABLE DICT_LEAF_ELEMENTS ADD
      String20 NVARCHAR(4000), String21 NVARCHAR(4000), String22 NVARCHAR(4000), String23 NVARCHAR(4000), String24 NVARCHAR(4000),
      String25 NVARCHAR(4000), String26 NVARCHAR(4000), String27 NVARCHAR(4000), String28 NVARCHAR(4000),String29 NVARCHAR(4000),
      String30 NVARCHAR(4000), String31 NVARCHAR(4000), String32 NVARCHAR(4000), String33 NVARCHAR(4000),String34 NVARCHAR(4000),
      String35 NVARCHAR(4000), String36 NVARCHAR(4000), String37 NVARCHAR(4000), String38 NVARCHAR(4000),String39 NVARCHAR(4000),
      String40 NVARCHAR(4000), String41 NVARCHAR(4000), String42 NVARCHAR(4000), String43 NVARCHAR(4000),String44 NVARCHAR(4000),
      String45 NVARCHAR(4000), String46 NVARCHAR(4000), String47 NVARCHAR(4000), String48 NVARCHAR(4000),String49 NVARCHAR(4000)    
  END
END
ELSE
BEGIN
  IF ((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'STRING20' AND TABLE_NAME = 'DICT_LEAF_ELEMENTS')=0)
  BEGIN
  ALTER TABLE DICT_LEAF_ELEMENTS ADD
      String20 NVARCHAR(MAX), String21 NVARCHAR(MAX), String22 NVARCHAR(MAX), String23 NVARCHAR(MAX), String24 NVARCHAR(MAX),
      String25 NVARCHAR(MAX), String26 NVARCHAR(MAX), String27 NVARCHAR(MAX), String28 NVARCHAR(MAX),String29 NVARCHAR(MAX),
      String30 NVARCHAR(MAX), String31 NVARCHAR(MAX), String32 NVARCHAR(MAX), String33 NVARCHAR(MAX),String34 NVARCHAR(MAX),
      String35 NVARCHAR(MAX), String36 NVARCHAR(MAX), String37 NVARCHAR(MAX), String38 NVARCHAR(MAX),String39 NVARCHAR(MAX),
      String40 NVARCHAR(MAX), String41 NVARCHAR(MAX), String42 NVARCHAR(MAX), String43 NVARCHAR(MAX),String44 NVARCHAR(MAX),
      String45 NVARCHAR(MAX), String46 NVARCHAR(MAX), String47 NVARCHAR(MAX), String48 NVARCHAR(MAX),String49 NVARCHAR(MAX)
  END
  ELSE
  BEGIN
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String20 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String21 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String22 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String23 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String24 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String25 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String26 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String27 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String28 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String29 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String30 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String31 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String32 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String33 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String34 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String35 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String36 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String37 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String38 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String39 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String40 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String41 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String42 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String43 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String44 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String45 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String46 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String47 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String48 NVARCHAR(MAX)
  ALTER TABLE DICT_LEAF_ELEMENTS ALTER COLUMN String49 NVARCHAR(MAX) 
  END
END;

UPDATE SYS_CONFIG SET HIDDEN = '1' WHERE CONFIG_KEY = 'dac.index.rebuild.days.of.month';
