IF NOT EXISTS (
  SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'SUPER_APPLICATION_USER') AND name = 'INITLOGIN_DONE'
) BEGIN 
	ALTER TABLE SUPER_APPLICATION_USER ADD INITLOGIN_DONE CHAR(1) DEFAULT 'N'
END;
IF NOT EXISTS (
  SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'APPLICATION_USER') AND name = 'INITLOGIN_DONE'
) BEGIN 
	ALTER TABLE APPLICATION_USER ADD INITLOGIN_DONE CHAR(1) DEFAULT 'N'
END;

alter table pm_parameter_config alter column list_values text;