UPDATE SYS_CONFIG SET RESTART_REQUIRED = '0' WHERE APPLICATION = 'cas' AND CONFIG_KEY = 'failed.login.attempts';
UPDATE SYS_CONFIG SET APPLICATION = 'application', RESTART_REQUIRED = '0' WHERE APPLICATION = 'console' AND CONFIG_KEY = 'enforce.password.history';
UPDATE SYS_CONFIG SET APPLICATION = 'reporter', CONFIG_KEY = 'use.past.data.for.monitoring', RESTART_REQUIRED = '0' WHERE APPLICATION = 'dms' AND CONFIG_KEY = 'reporter.use.past.data.for.monitoring';
UPDATE SYS_CONFIG SET APPLICATION = 'reporter', CONFIG_KEY = 'show.sharepoint', RESTART_REQUIRED = '0' WHERE APPLICATION = 'dms' AND CONFIG_KEY = 'reporter.show.sharepoint';

INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('DELETE', '/api/v1/enrolledData/search/remove/{id:[0-9]+}', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrolledData/findById/{id:[0-9]+}', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrolledData/search/fields', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrolledData/search/savedlist', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrolledData/search/savedlist/{name:.+}', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/enrolledData/search', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/enrolledData/search/add', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/pdpPlugin/list', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/pdpPlugin/add', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/pdpPlugin/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('PUT', '/api/v1/pdpPlugin/modify', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/pdpPlugin/modifyWithAttachment', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('DELETE', '/api/v1/pdpPlugin/delete/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('DELETE', '/api/v1/pdpPlugin/bulkDelete', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('PUT', '/api/v1/pdpPlugin/deploy/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('PUT', '/api/v1/pdpPlugin/bulkDeploy', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('PUT', '/api/v1/pdpPlugin/deactivate/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('PUT', '/api/v1/pdpPlugin/bulkDeactivate', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/pdpPlugin/downloadFile/{pluginId:[0-9]+}/{fileId:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/tools/property/findAll', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');


CREATE TABLE PDP_PLUGINS (
    [ID]                 [numeric] (18, 0) IDENTITY(1,1) NOT NULL,
    [NAME]               [nvarchar] (255) NOT NULL,
    [DESCRIPTION]        [nvarchar] (4000),
    [STATUS]             [varchar] (10) NOT NULL,
    [ACTIVE_FROM]        [numeric] (18,0),
    [ACTIVE_TO]          [numeric] (18,0),
    [CREATED_DATE]       [numeric] (18,0),
    [MODIFIED_DATE]      [numeric] (18,0),
    CONSTRAINT PDP_PLUGINS_PK PRIMARY KEY ( [ID] )
);

CREATE TABLE PDP_PLUGIN_FILES (
    [ID]                 [numeric] (18, 0) IDENTITY(1,1) NOT NULL,
    [PLUGIN_ID]          [numeric] (18, 0) NOT NULL,
    [TYPE]               [varchar] (15) NOT NULL,
    [NAME]               [nvarchar] (260) NOT NULL,
    [CONTENT]            [varbinary] (MAX) NULL,
    [MODIFIED_DATE]      [numeric] (18,0),
    CONSTRAINT PDP_PLUGIN_FILES_PK PRIMARY KEY ( [ID] ),
    CONSTRAINT PLUGIN_ID_FK FOREIGN KEY (PLUGIN_ID) REFERENCES PDP_PLUGINS
);

UPDATE SYS_CONFIG SET PATTERN = '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'spring.mail.properties.mail.smtp.from';
UPDATE SYS_CONFIG SET PATTERN = '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'cc.mail.default.to';
UPDATE SYS_CONFIG SET PATTERN = '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$' WHERE APPLICATION = 'cas' AND CONFIG_KEY = 'cas.authn.pm.reset.mail.from';

DELETE FROM ACCESS_CONTROL WHERE URL_PATTERN IN ('/api/v1/tools/createOrUpdateTask/{taskId:[0-9]+}', '/api/v1/tools/executeTask/{taskId:[0-9]+}', '/api/v1/tools/findAll', '/api/v1/tools/findCommands/{toolId:[0-9]+}', '/api/v1/tools/findParameters/{commandId:[0-9]+}', '/api/v1/tools/findTasks/{toolId:[0-9]+}', '/api/v1/tools/removeTask/{taskId:[0-9]+}', '/api/v1/tools/saveTask', '/api/v1/tools/task/{taskId:[0-9]+}', '/api/v1/tools/uploadFileExtra', '/api/v1/tools/getTemplate/{type:[A-Za-z]+}', '/api/v1/tools/getToolName/{toolId:[0-9]+}');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('DELETE', '/api/v1/enrollment/delete/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrollment/all', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrollment/id/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('GET', '/api/v1/enrollment/sync/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/enrollment/save', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/enrollment/upload/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
UPDATE ACCESS_CONTROL SET URL_PATTERN = '/api/v1/encrypt' WHERE URL_PATTERN = '/api/v1/tools/encrypt';

DROP VIEW TOOL_COMMAND_VIEW;
DROP TABLE TOOL_TASK_PARAM_VALUE;
DROP TABLE TOOL_TASK;
DROP TABLE TOOL_PARAMETER;
DROP TABLE TOOL_COMMAND;
DROP TABLE TOOL;

MERGE INTO SYS_CONFIG SC1 USING (SELECT 'application' AS APPLICATION, 'enrollmentservice.clientId' AS CONFIG_KEY) AS SC2 ON (SC1.APPLICATION = SC2.APPLICATION AND SC1.CONFIG_KEY = SC2.CONFIG_KEY)
WHEN MATCHED THEN UPDATE SET VALUE = 'nextlabs-cc-enrollment-service-client', DEFAULT_VALUE = 'nextlabs-cc-enrollment-service-client', VALUE_FORMAT = '', MAIN_GROUP = 'security', SUB_GROUP = 'enrollmentservice', MAIN_GROUP_ORDER = '40', SUB_GROUP_ORDER = '100', CONFIG_ORDER = '0', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '1', DATA_TYPE = 'text', FIELD_TYPE = 'text' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'Client id for enrollment service.', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES ('application', 'enrollmentservice.clientId', 'nextlabs-cc-enrollment-service-client', 'nextlabs-cc-enrollment-service-client', '', 'security', 'enrollmentservice', '40', '100', '0', '1', '1', '1', '0', '0', '1', 'text', 'text', '', '1', '', 'Client id for enrollment service.', CURRENT_TIMESTAMP, '-1' )&semi;

MERGE INTO SYS_CONFIG SC1 USING (SELECT 'application' AS APPLICATION, 'enrollmentservice.clientSecret' AS CONFIG_KEY) AS SC2 ON (SC1.APPLICATION = SC2.APPLICATION AND SC1.CONFIG_KEY = SC2.CONFIG_KEY)
WHEN MATCHED THEN UPDATE SET VALUE = '', DEFAULT_VALUE = '', VALUE_FORMAT = '{cipher}%s', MAIN_GROUP = 'security', SUB_GROUP = 'enrollmentservice', MAIN_GROUP_ORDER = '40', SUB_GROUP_ORDER = '100', CONFIG_ORDER = '1', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '1', UI = '0', ENCRYPTED = '1', RESTART_REQUIRED = '1', DATA_TYPE = 'text', FIELD_TYPE = 'text' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'Client secret for enrollment service.', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1'
WHEN NOT MATCHED THEN INSERT (APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES ('application', 'enrollmentservice.clientSecret', '', '', '{cipher}%s', 'security', 'enrollmentservice', '40', '100', '1', '1', '1', '1', '0', '1', '1', 'text', 'text', '', '1', '', 'Client secret for enrollment service.', CURRENT_TIMESTAMP, '-1' )&semi;


IF ((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'description' AND TABLE_NAME = 'DICT_ENROLLMENTS')=0)
BEGIN
  ALTER TABLE DICT_ENROLLMENTS ADD description varchar(4000)&semi
  ALTER TABLE DICT_ENROLLMENTS ADD created_by BIGINT&semi
  ALTER TABLE DICT_ENROLLMENTS ADD isSyncing TINYINT&semi
  ALTER TABLE DICT_ENROLLMENTS ADD created_date DATETIME&semi
  ALTER TABLE DICT_ENROLLMENTS ADD last_updated DATETIME&semi
  ALTER TABLE DICT_ENROLLMENTS ADD last_updated_by BIGINT&semi
END;

UPDATE DICT_ENROLLMENTS SET isSyncing = 0;
UPDATE DICT_ENROLLMENTS SET created_by = -1;
UPDATE DICT_ENROLLMENTS SET created_date = CURRENT_TIMESTAMP;
UPDATE DICT_ENROLLMENTS SET last_updated_by = -1;
UPDATE DICT_ENROLLMENTS SET last_updated = CURRENT_TIMESTAMP;

ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_ISSYNCING DEFAULT 0 FOR isSyncing;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_CREATED_BY DEFAULT -1 FOR created_by;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_CREATED_DATE DEFAULT CURRENT_TIMESTAMP FOR created_date;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_LAST_UPDATED_BY DEFAULT -1 FOR last_updated_by;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_LAST_UPDATED DEFAULT CURRENT_TIMESTAMP FOR last_updated;

-- We can do this more simply. We are creating and dropping constaints more often than
-- we need to. Still, this works.
ALTER TABLE DICT_ENROLLMENTS DROP CONSTRAINT DF_ISSYNCING;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN isSyncing TINYINT NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_ISSYNCING DEFAULT 0 FOR isSyncing;

ALTER TABLE DICT_ENROLLMENTS DROP CONSTRAINT DF_CREATED_BY;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN created_by BIGINT NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_CREATED_BY DEFAULT -1 FOR created_by;

ALTER TABLE DICT_ENROLLMENTS DROP CONSTRAINT DF_CREATED_DATE;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN created_date DATETIME NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_CREATED_DATE DEFAULT (getdate()) FOR created_date;

ALTER TABLE DICT_ENROLLMENTS DROP CONSTRAINT DF_LAST_UPDATED_BY;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN last_updated_by BIGINT NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_LAST_UPDATED_BY DEFAULT -1 FOR last_updated_by;

ALTER TABLE DICT_ENROLLMENTS DROP CONSTRAINT DF_LAST_UPDATED;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN last_updated DATETIME NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ADD CONSTRAINT DF_LAST_UPDATED DEFAULT (getdate()) FOR last_updated;

INSERT INTO ACCESS_CONTROL (REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES ('POST', '/api/v1/enrollment/validate', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');

UPDATE SYS_CONFIG SET VALUE = '120', DEFAULT_VALUE = '120' WHERE CONFIG_KEY = 'dashboard.widget.refresh.interval';

UPDATE SYS_CONFIG SET VALUE = 'https://docs.nextlabs.com/cc/2021.03' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'help.url.base';






