UPDATE SYS_CONFIG SET RESTART_REQUIRED = '0' WHERE APPLICATION = 'cas' AND CONFIG_KEY = 'failed.login.attempts';
UPDATE SYS_CONFIG SET APPLICATION = 'application', RESTART_REQUIRED = '0' WHERE APPLICATION = 'console' AND CONFIG_KEY = 'enforce.password.history';
UPDATE SYS_CONFIG SET APPLICATION = 'reporter', CONFIG_KEY = 'use.past.data.for.monitoring', RESTART_REQUIRED = '0' WHERE APPLICATION = 'dms' AND CONFIG_KEY = 'reporter.use.past.data.for.monitoring';
UPDATE SYS_CONFIG SET APPLICATION = 'reporter', CONFIG_KEY = 'show.sharepoint', RESTART_REQUIRED = '0' WHERE APPLICATION = 'dms' AND CONFIG_KEY = 'reporter.show.sharepoint';

INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'DELETE', '/api/v1/enrolledData/search/remove/{id:[0-9]+}', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrolledData/findById/{id:[0-9]+}', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrolledData/search/fields', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrolledData/search/savedlist', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrolledData/search/savedlist/{name:.+}', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/enrolledData/search', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/enrolledData/search/add', 'hasAnyAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/pdpPlugin/list', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/pdpPlugin/add', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/pdpPlugin/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'PUT', '/api/v1/pdpPlugin/modify', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/pdpPlugin/modifyWithAttachment', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'DELETE', '/api/v1/pdpPlugin/delete/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'DELETE', '/api/v1/pdpPlugin/bulkDelete', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'PUT', '/api/v1/pdpPlugin/deploy/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'PUT', '/api/v1/pdpPlugin/bulkDeploy', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'PUT', '/api/v1/pdpPlugin/deactivate/{id:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'PUT', '/api/v1/pdpPlugin/bulkDeactivate', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/pdpPlugin/downloadFile/{pluginId:[0-9]+}/{fileId:[0-9]+}', 'hasAuthority(''MANAGE_PDP_PLUGIN'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/tools/property/findAll', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');

CREATE TABLE PDP_PLUGINS (
    ID                 BIGINT NOT NULL,
    NAME               VARCHAR(255) NOT NULL,
    DESCRIPTION        VARCHAR(4000),
    STATUS             VARCHAR(10) NOT NULL,
    ACTIVE_FROM        BIGINT,
    ACTIVE_TO          BIGINT,
    CREATED_DATE       BIGINT,
    MODIFIED_DATE      BIGINT,
    CONSTRAINT PDP_PLUGINS_PK PRIMARY KEY (ID)
);

CREATE TABLE PDP_PLUGIN_FILES (
    ID                 BIGINT NOT NULL,
    PLUGIN_ID          BIGINT NOT NULL,
    TYPE               VARCHAR(15) NOT NULL,
    NAME               VARCHAR(260) NOT NULL,
    CONTENT            BYTEA,
    MODIFIED_DATE      BIGINT,
    CONSTRAINT PDP_PLUGIN_FILES_PK PRIMARY KEY (ID),
    CONSTRAINT PLUGIN_ID_FK FOREIGN KEY (PLUGIN_ID) REFERENCES PDP_PLUGINS
);

UPDATE SYS_CONFIG SET PATTERN = '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'spring.mail.properties.mail.smtp.from';
UPDATE SYS_CONFIG SET PATTERN = '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'cc.mail.default.to';
UPDATE SYS_CONFIG SET PATTERN = '^[^\s@]+@[^\s@]+\.[^\s@]{2,}$' WHERE APPLICATION = 'cas' AND CONFIG_KEY = 'cas.authn.pm.reset.mail.from';

DELETE FROM ACCESS_CONTROL WHERE URL_PATTERN IN ('/api/v1/tools/createOrUpdateTask/{taskId:[0-9]+}', '/api/v1/tools/executeTask/{taskId:[0-9]+}', '/api/v1/tools/findAll', '/api/v1/tools/findCommands/{toolId:[0-9]+}', '/api/v1/tools/findParameters/{commandId:[0-9]+}', '/api/v1/tools/findTasks/{toolId:[0-9]+}', '/api/v1/tools/removeTask/{taskId:[0-9]+}', '/api/v1/tools/saveTask', '/api/v1/tools/task/{taskId:[0-9]+}', '/api/v1/tools/uploadFileExtra', '/api/v1/tools/getTemplate/{type:[A-Za-z]+}', '/api/v1/tools/getToolName/{toolId:[0-9]+}');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'DELETE', '/api/v1/enrollment/delete/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrollment/all', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrollment/id/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'GET', '/api/v1/enrollment/sync/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/enrollment/save', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/enrollment/upload/{id:[0-9]+}', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');
UPDATE ACCESS_CONTROL SET URL_PATTERN = '/api/v1/encrypt' WHERE URL_PATTERN = '/api/v1/tools/encrypt';

DROP VIEW tool_command_view;
DROP TABLE tool_task_param_value;
DROP TABLE tool_task;
DROP TABLE tool_parameter;
DROP TABLE tool_command;
DROP TABLE tool;

INSERT INTO SYS_CONFIG (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'application', 'enrollmentservice.clientId', 'nextlabs-cc-enrollment-service-client', 'nextlabs-cc-enrollment-service-client', '', 'security', 'enrollmentservice', '40', '100', '0', '1', '1', '1', '0', '0', '1', 'text', 'text', '', '1', '', 'Client id for enrollment service.', CURRENT_TIMESTAMP, '-1' )
ON CONFLICT (APPLICATION, CONFIG_KEY) DO UPDATE SET VALUE = 'nextlabs-cc-enrollment-service-client', DEFAULT_VALUE = 'nextlabs-cc-enrollment-service-client', VALUE_FORMAT = '', MAIN_GROUP = 'security', SUB_GROUP = 'enrollmentservice', MAIN_GROUP_ORDER = '40', SUB_GROUP_ORDER = '100', CONFIG_ORDER = '0', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '1', UI = '0', ENCRYPTED = '0', RESTART_REQUIRED = '1', DATA_TYPE = 'text', FIELD_TYPE = 'text' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'Client id for enrollment service.', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1';

INSERT INTO SYS_CONFIG (ID, APPLICATION, CONFIG_KEY, VALUE, DEFAULT_VALUE, VALUE_FORMAT, MAIN_GROUP, SUB_GROUP, MAIN_GROUP_ORDER, SUB_GROUP_ORDER, CONFIG_ORDER, HIDDEN, READ_ONLY, ADVANCED, UI, ENCRYPTED, RESTART_REQUIRED, DATA_TYPE, FIELD_TYPE, OPTIONS, REQUIRED, PATTERN, DESCRIPTION, MODIFIED_ON, MODIFIED_BY ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'application', 'enrollmentservice.clientSecret', '', '', '{cipher}%s', 'security', 'enrollmentservice', '40', '100', '1', '1', '1', '1', '0', '1', '1', 'text', 'text', '', '1', '', 'Client secret for enrollment service.', CURRENT_TIMESTAMP, '-1' )
ON CONFLICT (APPLICATION, CONFIG_KEY) DO UPDATE SET VALUE = '', DEFAULT_VALUE = '', VALUE_FORMAT = '{cipher}%s', MAIN_GROUP = 'security', SUB_GROUP = 'enrollmentservice', MAIN_GROUP_ORDER = '40', SUB_GROUP_ORDER = '100', CONFIG_ORDER = '1', HIDDEN = '1', READ_ONLY = '1', ADVANCED = '1', UI = '0', ENCRYPTED = '1', RESTART_REQUIRED = '1', DATA_TYPE = 'text', FIELD_TYPE = 'text' , OPTIONS = '', REQUIRED = '1', PATTERN = '', DESCRIPTION = 'Client secret for enrollment service.', MODIFIED_ON = CURRENT_TIMESTAMP, MODIFIED_BY = '-1';

DO $$
BEGIN
  ALTER TABLE DICT_ENROLLMENTS ADD description CHARACTER VARYING(4000)&semi
  ALTER TABLE DICT_ENROLLMENTS ADD issyncing BOOLEAN&semi
  ALTER TABLE DICT_ENROLLMENTS ADD created_by INT8&semi
  ALTER TABLE DICT_ENROLLMENTS ADD created_date TIMESTAMP&semi
  ALTER TABLE DICT_ENROLLMENTS ADD last_updated TIMESTAMP&semi
  ALTER TABLE DICT_ENROLLMENTS ADD last_updated_by INT8&semi
EXCEPTION
WHEN duplicate_column THEN NULL&semi
END&semi
$$ ;

UPDATE DICT_ENROLLMENTS SET issyncing = false;
UPDATE DICT_ENROLLMENTS SET created_by = -1;
UPDATE DICT_ENROLLMENTS SET created_date = CURRENT_TIMESTAMP;
UPDATE DICT_ENROLLMENTS SET last_updated_by = -1;
UPDATE DICT_ENROLLMENTS SET last_updated = CURRENT_TIMESTAMP;

ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN issyncing SET DEFAULT false;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN created_by SET DEFAULT -1;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN created_date SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN last_updated_by SET DEFAULT -1;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN last_updated SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN issyncing SET NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN created_date SET NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN last_updated_by SET NOT NULL;
ALTER TABLE DICT_ENROLLMENTS ALTER COLUMN last_updated SET NOT NULL;

INSERT INTO ACCESS_CONTROL (ID, REQUEST_METHOD, URL_PATTERN, EXPRESSION) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), 'POST', '/api/v1/enrollment/validate', 'hasAuthority(''ENROLLMENT_MANAGEMENT'')');

UPDATE SYS_CONFIG SET VALUE = '120', DEFAULT_VALUE = '120' WHERE CONFIG_KEY = 'dashboard.widget.refresh.interval';

UPDATE SYS_CONFIG SET VALUE = 'https://docs.nextlabs.com/cc/2021.03' WHERE APPLICATION = 'application' AND CONFIG_KEY = 'help.url.base';
